export const GEOCODING_FETCHING = 'GEOCODING_FETCHING';
export const GEOCODING_FETCHING_ERROR = 'GEOCODING_FETCHING_ERROR';
export const WEATHER_FETCHING = 'WEATHER_FETCHING';
export const WEATHER_FETCHING_ERROR = 'WEATHER_FETCHING_ERROR';
