export const GEOCODING_FETCHING = 'GEOCODING_FETCHING';
export const GEOCODING_FETCHING_ERROR = 'GEOCODING_FETCHING_ERROR';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_CITY_TO_TRACKED_LIST = 'SET_CITY_TO_TRACKED_LIST';
export const WEATHER_FETCHING = 'WEATHER_FETCHING';
export const WEATHER_FETCHING_ERROR = 'WEATHER_FETCHING_ERROR';
export const UPDATE_CITY_WEATHER = 'UPDATE_CITY_WEATHER';
